# Custom Language File for Launcher Customizer

[ejs.app]
title = "Freaky Fish Launcher"

[ejs.landing]
mediaDiscordURL = "https://discord.gg/wW47QKFGwZ"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "I uhhh welcome to freaky fish"
welcomeDescription = "just try to not get /kill by the owner ig"
welcomeDescCTA = "you sure you wanna join?"
